name: Render-Book

on:
  push:
    branches:
      - main

jobs:
  bookdown:
    name: Build and Render Book
    runs-on: ubuntu-22.04
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Set up Pandoc
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Restore R package cache
      - name: Restore R package cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-packages-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-packages-

      # Install required R packages using DESCRIPTION file
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("devtools"))'
          Rscript -e 'devtools::install_deps()'

      # Save R package cache 
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-packages-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-packages-

      # Render the book
      - name: Render book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd")'

      # Upload rendered book as an artifact
      - name: Upload rendered book
        uses: actions/upload-artifact@v4
        with:
          name: _book
          path: _book/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    needs: bookdown
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Download the artifact (_book) from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: _book
          path: _book

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _book 
          branch: gh-pages  

